# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: ryank90/action-hugo-firebase-deploy@master
        with:
          firebase-token: ${{ secrets.firebase_token }}
          alias: blogs-toku345
          hugo-params: --minify
